// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC506Gu_E8h_7JJOuQmtLCeireVaXnWkqw',
    appId: '1:10339774435:web:c8fcdd1d79de9e02443ad6',
    messagingSenderId: '10339774435',
    projectId: 'sparrow-ad1f8',
    authDomain: 'sparrow-ad1f8.firebaseapp.com',
    storageBucket: 'sparrow-ad1f8.appspot.com',
    measurementId: 'G-B6Z6315L5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAspLoBsDaqW2K_p5i8P34lsDmSqJLy92c',
    appId: '1:10339774435:android:7bf35914b497380f443ad6',
    messagingSenderId: '10339774435',
    projectId: 'sparrow-ad1f8',
    storageBucket: 'sparrow-ad1f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLJjzavORbf56kIByjvE2cvIUwhDhsiPc',
    appId: '1:10339774435:ios:a73641b17e949eb8443ad6',
    messagingSenderId: '10339774435',
    projectId: 'sparrow-ad1f8',
    storageBucket: 'sparrow-ad1f8.appspot.com',
    iosBundleId: 'com.example.sparrow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLJjzavORbf56kIByjvE2cvIUwhDhsiPc',
    appId: '1:10339774435:ios:c4e5d8379f80d86b443ad6',
    messagingSenderId: '10339774435',
    projectId: 'sparrow-ad1f8',
    storageBucket: 'sparrow-ad1f8.appspot.com',
    iosBundleId: 'com.example.sparrow.RunnerTests',
  );
}
